### PR TITLE
fix: don't throw an error when a pr template is not found

### LINKED ISSUE #9: Ignore "not found" error when default pr template is not found
When the PR template is not found, the action can fail.

See:
* https://github.com/dequelabs/attest-browser-extensions/runs/400857604
* https://github.com/dequelabs/axe-linter/actions/runs/72731048

We should probably try to ignore and and continue with the action.

```js
try {
  response = octokit.foobar()
} catch (err) {
  if (err.message === 'Not Found') {
    throw new Error('Unable to fetch PR template')
  }
  throw err
}
```

### PR DESCRIPTION
**Pull request by scurker**
Closes #9 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [x] Follows the commit message policy, appropriate for next version
- [x] Code is reviewed for security

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -43,7 +54,9 @@ async function run(): Promise<void> {
       body ||
       Buffer.from(
         // eslint-disable-next-line @typescript-eslint/no-explicit-any
-        (pullRequestTemplate as any).content,
+        pullRequestTemplate
```
Comment (stephenmathieson) [inline src/main.ts:57]: It might make more sense to move this condition up a line:

```
body || pullRequestTemplate
  ? Buffer.from(pullRequestTemplate.content, 'base64')
  : ''
```

Since `Buffer.from('')` always return `''`.

Comment (scurker) [reply src/main.ts:57]: Not 100% sure why, but tests are failing when I change it, so I'll just leave as is
